const KEY='messenger17-state-v1';
const $=s=>document.querySelector(s);
const app=$('#app');
const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
const now=()=>new Date().toISOString();
const fmt=t=>new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(t));
const icons={chats:'💬',friends:'🤝',groups:'👥',channels:'#',news:'📰',settings:'⚙️'};
let state=load();let current=localStorage.getItem('messenger17-current')||null;let screen='chats';let activeChat=null;let activeRoom=null;let sidebar=false;
function load(){const s=localStorage.getItem(KEY);if(s)return JSON.parse(s);return{users:[],requests:[],friends:[],chats:[],messages:[],groups:[],channels:[],news:[],theme:'premium'}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function me(){return state.users.find(u=>u.id===current)}
function initials(n='M17'){return n.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'M'}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function setTheme(t){state.theme=t;save();document.documentElement.dataset.theme=t==='premium'?'':t}
setTheme(state.theme||'premium');
function notify(t){const n=document.createElement('div');n.className='toast';n.textContent=t;Object.assign(n.style,{position:'fixed',left:'50%',bottom:'24px',zIndex:99,transform:'translateX(-50%)',padding:'14px 18px',border:'1px solid var(--line)',borderRadius:'18px',background:'var(--panel2)',backdropFilter:'blur(18px)',boxShadow:'var(--shadow)',fontWeight:900});document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function render(){if(!me())return renderAuth();renderApp()}
function renderAuth(){app.innerHTML=`<main class="screen"><section class="auth"><div class="side"><div class="brand"><div class="logo">M17</div><span>Messenger17</span></div><h1>Мессенджер, который открывается сразу</h1><p>Без Supabase, без настроек: регистрация, друзья по согласию, личные чаты, группы, каналы, новости и темы прямо в браузере.</p><div class="chips"><span>Friends approval</span><span>Local secure storage</span><span>Mobile ready</span></div></div><form class="card form" id="authForm"><p class="eyebrow" id="authMode">Вход</p><h2 id="authTitle">Вернуться в сеть</h2><label class="regOnly" style="display:none">Ник<input name="username" placeholder="kans1x"></label><label class="regOnly" style="display:none">Имя<input name="name" placeholder="Артём"></label><label>Email<input name="email" type="email" placeholder="you@mail.com" required></label><label>Пароль<input name="pass" type="password" placeholder="••••••••" required></label><p class="msg" id="authMsg"></p><button class="btn">Войти</button><button class="ghost" type="button" id="toggleAuth">Создать аккаунт</button></form></section></main>`;let mode='login';$('#toggleAuth').onclick=()=>{mode=mode==='login'?'reg':'login';$('.regOnly').style.display=mode==='reg'?'grid':'none';document.querySelectorAll('.regOnly')[1].style.display=mode==='reg'?'grid':'none';$('#authMode').textContent=mode==='reg'?'Регистрация':'Вход';$('#authTitle').textContent=mode==='reg'?'Создать аккаунт':'Вернуться в сеть';$('#toggleAuth').textContent=mode==='reg'?'У меня уже есть аккаунт':'Создать аккаунт';$('#authForm .btn').textContent=mode==='reg'?'Зарегистрироваться':'Войти'};$('#authForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),email=f.get('email').trim().toLowerCase(),pass=f.get('pass');if(mode==='reg'){const username=f.get('username').trim();if(!username)return $('#authMsg').textContent='Введи ник';if(state.users.some(u=>u.email===email||u.username.toLowerCase()===username.toLowerCase()))return $('#authMsg').textContent='Такой пользователь уже есть';const u={id:uid(),email,pass,username,name:f.get('name').trim()||username,status:'В сети',created:now()};state.users.push(u);current=u.id;localStorage.setItem('messenger17-current',current);save();render();return}const u=state.users.find(u=>u.email===email&&u.pass===pass);if(!u)return $('#authMsg').textContent='Неверный email или пароль';current=u.id;localStorage.setItem('messenger17-current',current);render()}}
function nav(){return ['chats','friends','groups','channels','news','settings'].map(id=>`<button class="${screen===id?'active':''}" data-nav="${id}">${icons[id]} <span>${({chats:'Чаты',friends:'Друзья',groups:'Группы',channels:'Каналы',news:'Новости',settings:'Настройки'})[id]}</span>${id==='friends'&&incoming().length?`<b>${incoming().length}</b>`:''}</button>`).join('')}
function renderApp(){const u=me();app.innerHTML=`<div class="app"><aside class="sidebar ${sidebar?'open':''}"><div class="brand"><div class="logo">M17</div><span>Messenger17</span><button class="icon mobile" id="close">✕</button></div><div class="mini"><div class="avatar">${initials(u.name||u.username)}</div><div><strong>${esc(u.name||u.username)}</strong><span>@${esc(u.username)}</span></div></div><nav class="nav">${nav()}</nav><button class="ghost logout" id="logout">Выйти</button></aside><div class="backdrop ${sidebar?'show':''}" id="backdrop"></div><main class="work"><header class="top"><button class="icon mobile" id="menu">☰</button><div><p class="eyebrow">Online interface</p><h1>${title()}</h1></div><div class="actions"><button class="icon" onclick="notify('Уведомления будут здесь')">🔔</button><select id="theme">${['premium','neon','purple','light'].map(t=>`<option value="${t}" ${state.theme===t?'selected':''}>${t}</option>`).join('')}</select></div></header>${content()}</main><nav class="bottom">${['chats','friends','groups','channels','news'].map(id=>`<button class="${screen===id?'active':''}" data-nav="${id}">${icons[id]}<span>${title(id)}</span></button>`).join('')}</nav></div>`;bind()}
function title(id=screen){return{chats:'Чаты',friends:'Друзья',groups:'Группы',channels:'Каналы',news:'Новости',settings:'Настройки'}[id]}
function bind(){document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{screen=b.dataset.nav;sidebar=false;activeChat=null;activeRoom=null;render()});$('#logout').onclick=()=>{current=null;localStorage.removeItem('messenger17-current');render()};$('#menu')?.addEventListener('click',()=>{sidebar=true;render()});$('#close')?.addEventListener('click',()=>{sidebar=false;render()});$('#backdrop')?.addEventListener('click',()=>{sidebar=false;render()});$('#theme').onchange=e=>{setTheme(e.target.value);render()};bindForms()}
function content(){return{chats:chats(),friends:friends(),groups:communities('groups'),channels:communities('channels'),news:news(),settings:settings()}[screen]}
function myFriendIds(){const id=current;return state.friends.filter(f=>f.a===id||f.b===id).map(f=>f.a===id?f.b:f.a)}
function incoming(){return state.requests.filter(r=>r.to===current&&r.status==='pending')}
function directChatWith(id){return state.chats.find(c=>c.type==='direct'&&c.members.includes(current)&&c.members.includes(id))}
function chats(){const cs=state.chats.filter(c=>c.members.includes(current));if(!activeChat&&cs[0]&&window.innerWidth>860)activeChat=cs[0].id;const c=cs.find(x=>x.id===activeChat);return`<section class="chat-layout ${c?'chat-open':''}"><aside class="list"><h2>Диалоги</h2>${cs.length?cs.map(ch=>`<button class="chat ${activeChat===ch.id?'active':''}" data-chat="${ch.id}"><div class="avatar sm">${initials(chatName(ch))}</div><div><strong>${esc(chatName(ch))}</strong><span>${ch.type==='direct'?'личный чат':'группа'}</span></div></button>`).join(''):`<div class="empty"><h3>Чатов нет</h3><p>Добавь друга и прими заявку — чат создастся автоматически.</p></div>`}</aside><div class="chat-pane">${c?chatPane(c):`<div class="empty"><h3>Выбери чат</h3><p>На телефоне список и чат открываются отдельно.</p></div>`}</div></section>`}
function chatName(c){if(c.type!=='direct')return c.title;const other=c.members.find(x=>x!==current);const u=state.users.find(u=>u.id===other);return u?.name||u?.username||'Чат'}
function chatPane(c){const ms=state.messages.filter(m=>m.chat===c.id);return`<div class="chat-head"><button class="icon mobile" id="backChat">‹</button><div class="avatar">${initials(chatName(c))}</div><div><h2>${esc(chatName(c))}</h2><span>сообщения сохраняются в браузере</span></div></div><div class="messages" id="msgs">${ms.map(m=>`<div class="bubble ${m.from===current?'mine':''}"><small>${esc(state.users.find(u=>u.id===m.from)?.username||'user')} · ${fmt(m.time)}</small><p>${esc(m.text)}</p></div>`).join('')}</div><form class="composer" id="send"><input name="text" placeholder="Написать сообщение..."><button class="btn">➤</button></form>`}
function friends(){const friends=myFriendIds().map(id=>state.users.find(u=>u.id===id)).filter(Boolean);return`<section class="grid"><div class="pane"><h2>Добавить друга</h2><p>Пользователь получит заявку. Писать можно только после принятия.</p><form class="search" id="search"><input name="q" placeholder="Ник или имя"><button class="btn">Найти</button></form><div class="stack" id="results"></div></div><div class="pane"><h2>Заявки</h2>${incoming().length?`<div class="stack">${incoming().map(r=>{const u=state.users.find(u=>u.id===r.from);return`<div class="row"><div class="avatar sm">${initials(u?.name||u?.username)}</div><div><strong>${esc(u?.name||u?.username)}</strong><span>@${esc(u?.username)}</span></div><div class="row-actions"><button class="ok" data-accept="${r.id}">✓</button><button class="danger" data-decline="${r.id}">✕</button></div></div>`}).join('')}</div>`:`<div class="empty"><h3>Заявок нет</h3><p>Когда тебя добавят, запрос появится здесь.</p></div>`}</div><div class="pane full"><h2>Мои друзья</h2>${friends.length?`<div class="people">${friends.map(u=>`<div class="person"><div class="avatar">${initials(u.name||u.username)}</div><strong>${esc(u.name||u.username)}</strong><span>@${esc(u.username)}</span></div>`).join('')}</div>`:`<div class="empty"><h3>Список пуст</h3><p>Найди пользователя и отправь заявку.</p></div>`}</div></section>`}
function roomKey(type,id){return `${type}:${id}`}
function communities(type){const arr=state[type].filter(x=>x.owner===current||x.members?.includes(current));const label=type==='groups'?'группу':'канал';const title=type==='groups'?'Группы':'Каналы';if(!activeRoom&&arr[0]&&window.innerWidth>860)activeRoom=arr[0].id;const room=arr.find(x=>x.id===activeRoom);return`<section class="chat-layout ${room?'chat-open':''}"><aside class="list"><form class="form" id="community"><h2>Создать ${label}</h2><label>Название<input name="name" required placeholder="Messenger17 ${label}"></label><label>Описание<textarea name="desc" rows="3" placeholder="О чём пространство"></textarea></label><button class="btn">Создать</button></form><h2 style="margin-top:18px">Мои ${title.toLowerCase()}</h2>${arr.length?arr.map(x=>`<button class="chat ${activeRoom===x.id?'active':''}" data-room="${x.id}"><div class="avatar sm">${type==='groups'?'👥':'#'}</div><div><strong>${esc(x.name)}</strong><span>${esc(x.desc||'Нажми, чтобы писать')}</span></div></button>`).join(''):`<div class="empty"><h3>Пока пусто</h3><p>Создай первый ${label}, и тут появится место, куда можно писать.</p></div>`}</aside><div class="chat-pane">${room?roomPane(type,room):`<div class="empty"><h3>Выбери ${label}</h3><p>Тут будут сообщения и публикации.</p></div>`}</div></section>`}
function roomPane(type,room){const key=roomKey(type,room.id);const ms=state.messages.filter(m=>m.chat===key);const isChannel=type==='channels';return`<div class="chat-head"><button class="icon mobile" id="backRoom">‹</button><div class="avatar">${isChannel?'#':'👥'}</div><div><h2>${esc(room.name)}</h2><span>${isChannel?'публикации канала':'сообщения группы'} · ${esc(room.desc||'без описания')}</span></div></div><div class="messages" id="msgs">${ms.length?ms.map(m=>`<div class="bubble ${m.from===current?'mine':''}"><small>${esc(state.users.find(u=>u.id===m.from)?.username||'user')} · ${fmt(m.time)}</small><p>${esc(m.text)}</p></div>`).join(''):`<div class="empty"><h3>${isChannel?'Публикаций нет':'Сообщений нет'}</h3><p>${isChannel?'Напиши первый пост в канал.':'Напиши первое сообщение в группу.'}</p></div>`}</div><form class="composer" id="sendRoom"><input name="text" placeholder="${isChannel?'Написать пост в канал...':'Написать в группу...'}"><button class="btn">➤</button></form>`}
function news(){return`<section class="grid"><form class="pane form" id="post"><h2>Опубликовать новость</h2><label>Заголовок<input name="title" required></label><label>Текст<textarea name="body" rows="5" required></textarea></label><button class="btn">Опубликовать</button></form><div class="news">${state.news.length?state.news.slice().reverse().map(n=>`<article class="news-card"><small>${esc(state.users.find(u=>u.id===n.author)?.username||'admin')} · ${new Date(n.time).toLocaleDateString('ru-RU')}</small><h2>${esc(n.title)}</h2><p>${esc(n.body)}</p></article>`).join(''):`<div class="pane empty"><h3>Новостей нет</h3><p>Первый пост появится сразу после публикации.</p></div>`}</div></section>`}
function settings(){const u=me();return`<section class="grid"><form class="pane form" id="profile"><h2>Профиль</h2><label>Ник<input name="username" value="${esc(u.username)}"></label><label>Имя<input name="name" value="${esc(u.name)}"></label><label>Статус<input name="status" value="${esc(u.status||'В сети')}"></label><button class="btn">Сохранить</button></form><div class="pane"><h2>Темы</h2><div class="themes">${['premium','neon','purple','light'].map(t=>`<button class="theme ${state.theme===t?'active':''}" data-theme="${t}"><span class="dot ${t}"></span><strong>${t}</strong></button>`).join('')}</div></div></section>`}
function bindForms(){document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>{activeChat=b.dataset.chat;render()});document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>{activeRoom=b.dataset.room;render()});$('#backChat')?.addEventListener('click',()=>{activeChat=null;render()});$('#backRoom')?.addEventListener('click',()=>{activeRoom=null;render()});$('#send')?.addEventListener('submit',e=>{e.preventDefault();const text=new FormData(e.target).get('text').trim();if(!text)return;state.messages.push({id:uid(),chat:activeChat,from:current,text,time:now()});save();render();setTimeout(()=>$('#msgs')?.scrollTo(0,999999),0)});$('#sendRoom')?.addEventListener('submit',e=>{e.preventDefault();const text=new FormData(e.target).get('text').trim();if(!text||!activeRoom)return;state.messages.push({id:uid(),chat:roomKey(screen,activeRoom),from:current,text,time:now()});save();render();setTimeout(()=>$('#msgs')?.scrollTo(0,999999),0)});$('#search')?.addEventListener('submit',e=>{e.preventDefault();const q=new FormData(e.target).get('q').trim().toLowerCase();const box=$('#results');const found=state.users.filter(u=>u.id!==current&&(u.username.toLowerCase().includes(q)||u.name.toLowerCase().includes(q))).slice(0,12);box.innerHTML=found.length?found.map(u=>`<div class="row"><div class="avatar sm">${initials(u.name||u.username)}</div><div><strong>${esc(u.name||u.username)}</strong><span>@${esc(u.username)}</span></div><button class="ghost" data-add="${u.id}">Добавить</button></div>`).join(''):'<p class="msg">Никого не найдено</p>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>sendReq(b.dataset.add))});document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>answer(b.dataset.accept,true));document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=()=>answer(b.dataset.decline,false));$('#community')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const type=screen;const item={id:uid(),owner:current,members:[current],name:f.get('name').trim(),desc:f.get('desc').trim(),created:now()};state[type].push(item);activeRoom=item.id;save();notify('Создано, теперь сюда можно писать');render()});$('#post')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.news.push({id:uid(),author:current,title:f.get('title'),body:f.get('body'),time:now()});save();render()});$('#profile')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),u=me();u.username=f.get('username').trim();u.name=f.get('name').trim();u.status=f.get('status').trim();save();notify('Профиль сохранён');render()});document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{setTheme(b.dataset.theme);render()})}
function sendReq(to){if(myFriendIds().includes(to))return notify('Уже в друзьях');if(state.requests.some(r=>r.from===current&&r.to===to&&r.status==='pending'))return notify('Заявка уже отправлена');state.requests.push({id:uid(),from:current,to,status:'pending',time:now()});save();notify('Заявка отправлена')}
function answer(id,ok){const r=state.requests.find(r=>r.id===id);if(!r)return;r.status=ok?'accepted':'declined';if(ok){state.friends.push({id:uid(),a:r.from,b:r.to,time:now()});if(!directChatWith(r.from)){state.chats.push({id:uid(),type:'direct',members:[r.from,r.to],title:'',created:now()})}}save();render()}
render();
